### ISSUE TITLE
There is a bug in this code.

### ISSUE THREAD

**Issue by vitsum** [mnaei/RopstenSeglos#1]
I've found a little bug or feature in 61st line
[https://github.com/mnaei/RopstenSeglos/blob/6bf2417673531c3f63580710f47188d480c507c4/Exchange.sol#L61](https://github.com/mnaei/RopstenSeglos/blob/6bf2417673531c3f63580710f47188d480c507c4/Exchange.sol#L61)
 
`require (eth >= loanMinimum || eth <= loanMaximum)`

This line doesn't make sense because you can create trades without any limits. You should replace || with &&.

**Comment by mnaei** [comment]
Thank you for pointing that out.  The initial code was an 

if (true) throw;

Rather than 

require(true);

I made a quick edit and forgot to correct the error. I'll make the necessary changes.
